name: Container Push (Jetson)

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-jetson:
    runs-on: [self-hosted, Linux, ARM64, jetson]

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          file: Containerfile.cuda12jp6
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:jetson-latest
            ghcr.io/${{ github.repository }}:jetson-${{ github.sha }}
            ghcr.io/${{ github.repository }}:jetson-${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
